server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/users/**

            - id: post-service
              uri: http://localhost:8082
              predicates:
                - Path=/posts/**

            - id: comment-service
              uri: http://localhost:8083
              predicates:
                - Path=/comments/**

            - id: ai-service
              uri: http://localhost:8084
              predicates:
                - Path=/ai/**