INSERT INTO posts (title, content, author_id) VALUES
                                                  ('The Magic of Spring Boot: Simplifying Java Development',
                                                   'Spring Boot has revolutionized how developers build applications in Java. Gone are the days of complex XML configurations and endless boilerplate code. With its opinionated approach, Spring Boot provides a rapid application development experience, allowing you to get a project up and running in minutes. It intelligently configures your application based on the dependencies you include, making setup a breeze. Whether you''re building microservices or monolithic applications, Spring Boot’s auto-configuration and embedded servers mean you can focus on writing business logic, not wrestling with infrastructure. It truly makes Java development feel more intuitive and enjoyable.',
                                                   1),
                                                  ('Beyond the Basics: Essential Spring Boot Features You Need to Know',
                                                   'While simplicity is Spring Boot’s hallmark, its power lies in its rich set of features. Auto-configuration, as mentioned, is a game-changer, automatically setting up common components. But there''s more! Spring Boot Actuator provides production-ready features like monitoring and management endpoints, giving you deep insights into your running application. The starter dependencies simplify build configurations by pulling in all necessary transitive dependencies for specific functionalities. Add to that its support for externalized configuration, robust testing utilities, and easy integration with various data sources and cloud platforms, and you have a framework that''s not just easy to start with, but also incredibly powerful for scaling and maintaining complex applications.',
                                                   1),
                                                  ('Your First Steps: Building a Spring Boot Application from Scratch',
                                                   'Ready to dive into Spring Boot? The easiest way to kickstart your project is by using the Spring Initializr (start.spring.io). This web-based tool allows you to select your project metadata, Java version, and desired dependencies (like Web, JPA, H2 Database). Once generated, you can download a zip file, import it into your favorite IDE (IntelliJ IDEA, VS Code, Eclipse), and you''re ready to write your first controller or service. With minimal setup, you’ll have a runnable JAR file that includes an embedded server, making deployment incredibly straightforward. It''s an excellent way to quickly prototype ideas or begin developing robust, enterprise-grade applications.',
                                                   2);
